import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <title>LET Academy | La mejor academia de inglés online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./Icon.png" />
        <script id="setmore_script" type="text/javascript" src="https://storage.googleapis.com/fullintegration-live/webComponentAppListing/Container/setmoreIframeLive.js"></script><a style="float:none; position: fixed; right: -2px; top: 25%; display: block; z-index: 20000" id="Setmore_button_iframe" href="https://booking.setmore.com/scheduleappointment/53db59a2-b99d-421f-ac8a-48b901d50432"><img border="none" src="https://storage.googleapis.com/full-assets/setmore/images/1.0/Calendar/Setmore-Book-Now.png" alt="Book an appointment with LET Team using Setmore" /></a>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}

